/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ca2dsa;

import javax.swing.JOptionPane;

/**
 * @author Felipe Paneque
 * student number 23156635
 * 14/03/2025
 */
public class BloodTestSchedulerGUI extends javax.swing.JFrame {  
    //declare the 3 ADT's
    private final PriorityQueueClass pq;
    private Queue notAttendedQueue = new Queue();
    private SingleLinkedList attendedPatients = new SingleLinkedList();
    
    public BloodTestSchedulerGUI() {
        initComponents();
        //Adding patients to PQueue
        pq = new PriorityQueueClass();
        pq.addPatient(7,"Felipe Paneque", 23, "Dr.Tomas Turbando", "NO", true);
        pq.addPatient(10,"Murilo Batiuk",35, "Dr.Kelly Guissa", "YES", false);
        pq.addPatient(2,"Stefany Junges",25, "Dr.Tolin Rabando", "YES", true); 
        pq.addPatient(5,"Filip Zielinsky",21, "Dr.Lana del rey", "NO", false);
        pq.addPatient(4,"John Luis", 33, "Dr.Tomas Turbando", "NO", true);
        pq.addPatient(6,"Kyle Dodge",35, "Dr.Kelly Guissa", "YES", false);
        pq.addPatient(2,"Hailey Bieber",25, "Dr.Tolin Rabando", "YES", true); 
        pq.addPatient(1,"Michael Foive",21, "Dr.Lana del rey", "NO", false);
        pq.addPatient(7,"Amanda DaSanta", 23, "Dr.Tomas Turbando", "NO", true);
        pq.addPatient(10,"Trevor Philips ",55, "Dr.Kelly Guissa", "YES", false);
        pq.addPatient(8,"Tracey DaSanta",25, "Dr.Tolin Rabando", "YES", true); 
        pq.addPatient(9,"Franklin Clinton",23, "Dr.Lana del rey", "NO", false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        nextPatientBTN = new javax.swing.JButton();
        attendanceBTN = new javax.swing.JButton();
        patientsBTN = new javax.swing.JButton();
        shownPatientsBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        titleLBL.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        titleLBL.setText("Blood Test Scheduler");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(titleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(titleLBL)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        nextPatientBTN.setText("NEXT PATIENT TO BE ASSISTED");
        nextPatientBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPatientBTNActionPerformed(evt);
            }
        });

        attendanceBTN.setText("PATIENTS THAT DID NOT SHOW UP");
        attendanceBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceBTNActionPerformed(evt);
            }
        });

        patientsBTN.setText("PATIENTS IN THE QUEUE");
        patientsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientsBTNActionPerformed(evt);
            }
        });

        shownPatientsBTN.setText("PATIENTS THAT SHOWED UP");
        shownPatientsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shownPatientsBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextPatientBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(attendanceBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(shownPatientsBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientsBTN)
                    .addComponent(attendanceBTN))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextPatientBTN)
                    .addComponent(shownPatientsBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void patientsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientsBTNActionPerformed
        // TODO add your handling code here:
        displayTA.setText(pq.printPatients());
    }//GEN-LAST:event_patientsBTNActionPerformed

    private void attendanceBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceBTNActionPerformed
        // TODO add your handling code here:
        displayTA.setText(notAttendedQueue.toString());
       
    }//GEN-LAST:event_attendanceBTNActionPerformed

    private void nextPatientBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPatientBTNActionPerformed
        // TODO add your handling code here:
        while (!pq.isEmpty()) { // Loop until no more patients
            Patient patient = pq.nextPatient(); // Store patient before checking attendance

            int response = JOptionPane.showConfirmDialog(null,"Has the patient attended ?" + "\n" + patient.getBriefDetails(), "Confirm Attendance", JOptionPane.YES_NO_OPTION);
            //confirmDialog will return an int and not a boolean, 
            //YES_OPTION will return a 0, making it a true,
            //NO_OPTION will return a 1, making it a false.
            boolean attended = (response == JOptionPane.YES_OPTION);
            if (!attended) {
                //if did not attend, go to 5 people Queue; 
                notAttendedQueue.enqueue(patient);
            } else {
                //if attended, go to LinkedList;
                int index = attendedPatients.size() + 1;
                attendedPatients.addPatient(index, patient);
            }
            
            pq.removePatient(); // Remove patient from the priorityQueue regardless of attendance
        }
            
        JOptionPane.showMessageDialog(null, "No more patients waiting!");

    }//GEN-LAST:event_nextPatientBTNActionPerformed

    private void shownPatientsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shownPatientsBTNActionPerformed
        // TODO add your handling code here:
        displayTA.setText(attendedPatients.printPatients());
    }//GEN-LAST:event_shownPatientsBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BloodTestSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BloodTestSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BloodTestSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BloodTestSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BloodTestSchedulerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attendanceBTN;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextPatientBTN;
    private javax.swing.JButton patientsBTN;
    private javax.swing.JButton shownPatientsBTN;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
